### ISSUE TITLE
CompanyRepositoryInterface

### ISSUE THREAD

**Issue by ghost** [kylenoland/laravel-base-repository#1]
What should the CompanyRepositoryInterface look like?

**Comment by JeffreyDavidson** [comment]
Is there a way for you to explain this?

**Comment by kylenoland** [comment]
An "empty" CompanyRepositoryContract and CompanyRepository would look like this:

```
<?php namespace MyApp\Contracts;

use KyleNoland\EloquentFoundation\Contracts\BaseRepositoryContract;

interface CompanyRepositoryContract extends BaseRepositoryContract {

}
```

```
<?php namespace MyApp\Repositories;

use KyleNoland\EloquentFoundation\Repositories\BaseRepository;
use MyApp\Contracts\CompanyRepositoryContract;
use MyApp\Models\Company;

class CompanyRepository extends BaseRepository implements CompanyRepositoryContract {

    /**
     * Inject class dependencies
     *
     * @param Company $model
     */
    public function __construct(Company $model)
    {
        $this->model = $model;
    }

}
```

Then you're free to write to Company-specific methods by using your injected Eloquent model via $this->model. For instance, if you wanted a method on your CompanyRepository for getting a collection of Company records by state, you could do something like:

Write the interface signature in your CompanyRepositoryContract:

```
public function getByState($state);
```

Implement the method in your CompanyRepository:

```
public function getByState($state)
{
    return $this->model->where('state', $state)->get();
}
```

And then maybe in a controller you would do something like:

```
$texasCompanies = $this->companyRepo->getByState('TX');
```
